### ISSUE TITLE
change warning to say doesnt test current versions of browsers

### ISSUE THREAD

**Issue by dstorey** [w3c/wptdashboard#170]
Currently says doesn't test pre-release versions of Edge and Safari

Actually doesn't even test current versions of Edge and Safari.

**Comment by jeffcarp** [comment]
We should be testing at least the current public versions of browsers, otherwise that's a bug.

**Comment by jgraham** [comment]
I think we aren't necessarily because Sauce is a little behind. There is talk about moving to BrowserStack which allegedly might be more  up to date, at least with Edge.

We would of course do much better here if MS and Apple weren't tying browser version to OS versions, and then placing restrictive license requirements on those OSes that makes it impractical to provide them through a service like TravisCI.

**Comment by jgraham** [comment]
(and I think there has been discussion about getting Microsoft and Apple to provide their own results, but so far I haven't seen anything come of that).

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#24
