### ISSUE TITLE
The machine generates a shell script which takes the required files from the SHA and the modified run script and sends them to a machine in the pool.

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#397]
Subissue of https://github.com/w3c/wptdashboard/issues/394

**Comment by jugglinmike** [comment]
This operation is error-prone because it assumes that tests do not have dependencies that span WPT's file hierarchy. We have decided to delegate the operation of subdividing WPT to the WPT CLI tool partially to avoid this problem (since it operates via the dependency-aware manifest file). I'm closing this issue accordingly.
