### ISSUE TITLE
Make test runner test against the first SHA of the day

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#40]
Instead of having a scheduled job update the SHA all test runners should be testing against, we can just have all runners test against the first SHA committed that day.

**Comment by foolip** [comment]
I don't think this can be made robust. Whatever the condition for testing commits for "is today" is and whatever order one takes at merge commits, later (merge) commits could make it such that another commit is the first that matches the "is today" condition. This is just a problem with Git, and that one can't tell what the master branch has pointed to in the past.

What is the current state of this, is the job that picks a commit still running?

**Comment by jgraham** [comment]
Assuming each commit comes from a PR, you could find the first PR to merge today (whenever that is), and use the merge_commit_sha property to get the corresponding HEAD of master. It does add a dependency on the GitHub API though.

**Comment by foolip** [comment]
Yeah, something around PR status should be robust against later changes in Git history. `curl https://api.github.com/repos/w3c/web-platform-tests/pulls/7233` has `"merged_at": "2017-09-04T07:19:20Z",63763763ad8fc064ad03ec1fa"` and as long as a PR isn't opened and merged again I guess that would never change.

I think one would have to inspect all 7000+ PRs, however, since any of the PRs could be the earliest one merged today, and agreeing on (say) 100 PRs but checking at different times could lead to different results.

Overall, I think it'd be less work for everyone to pick a commit per day and publish it somewhere. It would be fairly simple to set up a cron job that adds a new tag in the repo itself once per day, would that be better or worse than having the dashboard publish it?

**Comment by jgraham** [comment]
I agree that your method is simpler. But something like:
```
curl 'https://api.github.com/search/issues?q=type:pr+repo:w3c/web-platform-tests+is:merged+merged:>=2017-09-04'
```
Can give you PRs that were merged today.

**Comment by foolip** [comment]
Ah, I guess as long as the number of PRs in a day never exceeds 100, no pagination code would be needed, and that'd be robust.

I think this choice is ultimately up to @bobholt and what @thejohnjansen would prefer to work with.

**Comment by gsnedders** [comment]
A potentially stupid but workable solution would be to simply store the "current test run commit" somewhere, and if the commit date of that commit is greater than 24 hours ago then change it to the current tip of master. No faffing around trying to figure out the "first commit of the day" or anything—just set it to be "one commit per day" with it chosen pretty arbitrarily.

**Comment by jeffcarp** [comment]
> simply store the "current test run commit" somewhere

The first part of what you mentioned was in the original design doc and I implemented it at some point then removed it in anticipation that #40 (this issue) would be a better solution. I resurrected the code from an old private fork of the repo and [uploaded it to a branch](https://github.com/GoogleChrome/wptdashboard/compare/daily-wpt-sha-fetch) in case it could come in useful.

**Comment by foolip** [comment]
@gsnedders, yep, just recording what master points to at a regular 24-hour interval is what I had in mind, and it looks like that's what @jeffcarp's resurrected code does.

**Comment by foolip** [comment]
@mattl, this is also related to the Q4 [Consistent results for all browsers are updated every 24 hours](https://docs.google.com/document/d/1GZquS8Jra47E5hIMH2ObOb_7oQFgk8f9MptUAjF0LFI/edit#heading=h.qxotds9ar227) OKR and https://github.com/w3c/wptdashboard/issues/138.

**Comment by lukebjerring** [comment]
Seems to me that if you make this the behaviour, then https://github.com/w3c/wptdashboard/issues/138 becomes redundant (excepting errors) as the runs will all be against that hash.

**Comment by jeffcarp** [comment]
@lukebjerring yes that's correct if the runs were successful 100% of the time, but #138 might still be necessary in order to lessen the impact of the occasional infra hiccup

**Comment by lukebjerring** [comment]
@mattl - I'm under the impression that the way that you're choosing which SHA to use makes this issue relevant again.

Note that it was closed via https://github.com/w3c/wptdashboard/blob/master/run/shas.py

**Comment by jugglinmike** [comment]
As of gh-522, we collect results on a regular schedule (once every 6 hours for Chrome and Firefox, once every 2 days for Edge and Safari). We identify the latest commit to WPT at this moment, and all subsequent testing operations reference that commit via its git SHA sum.

**Comment by foolip** [comment]
@jugglinmike, is it just luck that the slow runs line up with the fast ones in https://wpt.fyi/test-runs, or is there a coupling?

**Comment by jugglinmike** [comment]
> @jugglinmike, is it just luck that the slow runs line up with the fast ones
> in https://wpt.fyi/test-runs, or is there a coupling?

@foolip There is a kind of coupling, though I hesitate to use that word because of its negative connotation. The relationship is only expressed in the UI component, and it seems intentional. The relevant source code is here:

https://github.com/w3c/wptdashboard/blob/46aa4045f4283e3897b15120a6c7c6ff9399ff32/webapp/components/wpt-runs.html#L137-L148
