### ISSUE TITLE
Update: remove xvfb from script (was: xvfb should be optional)

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#444]

**Comment by jugglinmike** [comment]
The problem here is that we don't want to use `xvfb` in all cases. An additional flag could get us there, but there are other approaches we should consider.

For example, what about removing `xvfb-run` from `run.py` altogether? This would make `run.py` more portable overall. As far as I can tell, portability is the primary motivation for scripting in Python in the first place. That would let us use the same executable to run Edge locally (as opposed to remotely via Sauce Labs). We may have a similar need for virtual displays in Windows environments, but it won't be solved by `xvfb`.

**Comment by mattl** [comment]
I'm okay with that. We could leave providing a viable running solution to the machine itself, and perhaps use a headless mode if one exists as a last resort. I'll close out my PR for now.

**Comment by jugglinmike** [comment]
We addressed this issue via the introduction of a Buildbot-driven infrastructure (see gh-522).
