### ISSUE TITLE
Finish the wptd stats scoring stub-script 

### ISSUE THREAD

**Issue by mariestaver** [w3c/wptdashboard#477]
at https://github.com/foolip/ecosystem-infra-stats/blob/master/wpt-dashboard-stats.py

**Comment by foolip** [comment]
Oops, I just filed https://github.com/foolip/ecosystem-infra-stats/issues/6 which is kinda a dupe, but will leave it open anyway so it can be found from both repos.

Description of OKR scoring is the most explicit about what is needed I think: "Based on the latency from PR being merged in wpt to results for that or a later commit being shown on wpt.fyi for each browser individually. The score is the proportion of PRs×4 (number of browsers) where results were shown within 12 hours. (Measured on every PR in March.)"

The PRs that are "in March" are the ones that were landed in March, not where the test runs finish in March. (Small difference, but just to be consistent with how import is measured.)

To score the KR the raw data that's needed is just a tuple of 4 values (latencies) per PR and then what proportion of those are less than 12 hours, but it'll very likely help explain the score if we also have 50th and 90th percentile latency numbers, and the the same numbers broken down per browser instead aggregated. (Since some browsers will be running more regularly than others.)

**Comment by mariestaver** [comment]
@mattl -- The Ecosys team would also like a script to measure how many of the results after each update are showing the same SHA.  Do you think this should be a separate script, or an addition to this one?

**Comment by foolip** [comment]
That would be a separate script, and I think the input would be just https://wpt.fyi/test-runs. Basically it is the number of rows with 4 runs divided by the total number of rows in the period.

**Comment by mattl** [comment]
@foolip can you look at https://github.com/mattl/ecosystem-infra-stats/blob/master/wpt-dashboard-stats.py and see if that's getting useful information?

**Comment by foolip** [comment]
@mattl, sorry for taking so long, I'm getting to this now. The crucial part that is missing is "find the earliest run for each browser that *included* that PR", where this is now just matching on the sha exactly, in `if run['revision'] == foo`.

Since we've already decided to change how we're going to measure the reliability of the running infrastructure going forward, I will take it upon myself to measure this in ecosystem-infra-stats to get this quarter's OKR score.

**Comment by foolip** [comment]
But... spending some time on this, it's not so clear that we need the full git acrobatics @Hexcles and I discuss in https://github.com/foolip/ecosystem-infra-stats/issues/4. We could instead assume that *only* commits on master that have been tagged are tested, and then match by commit exactly, and just sort PRs by when they were merged. We shall see...

**Comment by foolip** [comment]
After spending some time last week looking at the runs and PRs, I think it's probably not a good idea to only match exactly. Whenever a tag is missing or master was updated outside of a PR and if the result is what's run on wpt.fyi, then ignoring that would make the stats look worse than they are, which is the wrong side to err on, IMHO.
