### ISSUE TITLE
Troubleshooting: Chrome run has been stalled for >12h

### ISSUE THREAD

**Issue by mariestaver** [w3c/wptdashboard#500]
We're pausing our ongoing work to stabilize and improve the system to address three runs that are not completing today.  Please use this issue to track the details of what we're trying and what works/doesn't.  Thanks!

**Comment by mattl** [comment]
I've manually added --test-types to run.py

command = [
                'xvfb-run', '--auto-servernum',
                './wpt', 'run',
		platform['browser_name'],
                '--test-types reftest,testharness',
            ]

Things were erroring out with BadStatusLine. I found that rebooting the machine fixed this, however with ` '--test-types reftest,testharness'` the tests don't seem to run at all. 

 wpt:stdout Using webdriver binary /root/web-platform-tests/_venv/bin/chromedriver
 wpt:stdout  0:01.43 INFO Updating test manifest /root/web-platform-tests/MANIFEST.json
 wpt:stdout  0:01.45 INFO STDOUT: INFO:manifest:Skipping manifest download because existing file is recent
 wpt:stdout  0:06.47 INFO STDOUT: INFO:manifest:Updating manifest
 wpt:stdout  0:18.72 INFO STDOUT: DEBUG:manifest:Opening manifest at /root/web-platform-tests/MANIFEST.json
 wpt:stdout  0:25.29 INFO Using 1 client processes
 wpt:stdout  0:25.42 SUITE_START: web-platform-test - running 0 tests
 wpt:stdout  0:25.43 INFO Running reftest tests
 wpt:stdout  0:25.49 INFO No reftest tests to run
 wpt:stdout  0:25.49 INFO Running wdspec tests
 wpt:stdout  0:25.50 INFO No wdspec tests to run
 wpt:stdout  0:25.50 INFO Running testharness tests
 wpt:stdout  0:25.50 INFO Starting http server on web-platform.test:8001
 wpt:stdout  0:25.50 INFO No testharness tests to run
 wpt:stdout  0:25.50 INFO Got 0 unexpected results
 wpt:stdout  0:25.50 SUITE_END
 wpt:stdout 
 wpt:stdout web-platform-test
 wpt:stdout ~~~~~~~~~~~~~~~~~
 wpt:stdout Ran 0 checks ()
 wpt:stdout Expected results: 0
 wpt:stdout OK
 wpt:stdout  0:25.51 INFO Starting http server on web-platform.test:8443
 wpt:stdout  0:25.61 INFO Closing logging queue
 wpt:stdout  0:25.61 INFO queue closed
Return code from wptrunner: 0
0 tests defined in chunk
No results found after 3 attempts. Giving up.
Finished WPT run
Creating summary of results
CRITICAL root Insufficient report data (Zero results available). Stopping.

**Comment by mattl** [comment]
Okay, Chrome is running its thing on the normal Chrome runner box now. I continue to fiddle with my personal runner.

**Comment by jgraham** [comment]
That is the wrong sytax for the test-types flag, it should be `--test-types testharness reftest`

**Comment by mattl** [comment]
Chrome successfully ran and we have a March 1st run on the dashboard.
