### ISSUE TITLE
Investigate using a Docker container to simplify test running

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#72]
Dependency management has proven to be difficult for test running, and as we add more browser versions and configurations it will only get more complex. One solution is to create one Docker image containing all the browsers and other dependencies we need to do a full test run. Including:

- Chrome Dev and Chromedriver binaries
- Firefox Nightly and Geckodriver binaries
- Firefox prefs
- The Sauce Connect binary
- A checkout of WPT and WPTD (we'd still need to fetch the latest commit)

Benefits of doing so would:
- Decrease the operational complexity and toil of managing the running infrastructure
- Allow us to more easily parallelize builds by [spinning up clusters of containers](https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/)
- Make the running portion of WPT Dashboard very portable, a stated goal of this project

One alternative to part of this is to add more capabilities to the auto-download feature of the `wpt run` script.

**Comment by jgraham** [comment]
So first: Firefox beta? Why are we testing with that rather than nightly? Testing with nightly would be much more helpful for developers.

I'm very interested in more capabilities being added to `wpt run`; I think that would help many contributors. That said I also see the appeal of a docker image; if we create one it would be nice to add tooling so that people can easily use the same image to run tests locally.

Note with some of the things you mentioned that there's time variability. Obviously Firefox and Chrome change, but so do e.g. the gecko prefs.

**Comment by jeffcarp** [comment]
> Why are we testing with that rather than nightly?

My mistake, I meant nightly - fixed.

In terms of downloading all the dependencies needed to run the tests, it sounds like all that functionality can be added to `wpt run`. A docker container would simplify deploying the initial starting copies of WPT and WPTD and would make spinning up clusters of test runners easier, but at the current state of the infrastructure (just a few VMs), it's probably overkill.

**Comment by jeffcarp** [comment]
Closed by #153
